changed plan command

diff --git a/.github/workflows/TF_Plan.yml b/.github/workflows/TF_Plan.yml
--- a/.github/workflows/TF_Plan.yml
+++ b/.github/workflows/TF_Plan.yml
@@ -76,9 +76,9 @@ jobs:
 
       - name: Terraform Plan
         id: plan
-        run: terraform plan --var-file=$TF_VARS --out=plan.tfplan
+        run: terraform plan -var-file="${{ inputs.path }}" -out=tfplan
         continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+    #   - name: Terraform Plan Status
+    #     if: steps.plan.outcome == 'failure'
+    #     run: exit 1
